services:
  web:
    container_name: ${WEB_APP_NAME}
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        ENV: development
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./src:/var/www/html/
    working_dir: /var/www/html/
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - mysql
    networks:
      - app_network

  mysql:
    image: mysql:8.0.30
    container_name: ${DB_APP_NAME}
    # restart: always
    ports:
      - ${MYSQL_PORT}:3306
    command:
      - --sql-mode=NO_ENGINE_SUBSTITUTION
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    env_file:
      - ./docker/config/dev.env
    environment:
      - BIND-ADDRESS=0.0.0.0
      - TZ=Asia/Tokyo
    volumes:
      - ./data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./schema:/var/tmp
    working_dir: /var/tmp
    networks:
      - app_network

  mail:
    image: axllent/mailpit:latest
    container_name: ${MAIL_APP_NAME}
    ports:
      - ${MAIL_SMTP_PORT}:1025
      - ${MAIL_HTTP_PORT}:8025
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
